config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }

  resources :users

  resources :budget_categories do
    resources :expenses
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'splash_screen#index'
end

app/models/budget_category.rb
class BudgetCategory < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :budget_category_expenses, dependent: :destroy
  has_many :expenses, through: :budget_category_expenses, dependent: :destroy

  validates :name, presence: true
  validates :icon, presence: true

  def total
    expenses.sum(:amount)
  end
end

app/controllers/budget_categories_controller.rb
class BudgetCategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_budget_category, only: %i[show edit update destroy]

  # GET /budget_categories or /budget_categories.json
  def index
    @budget_categories = BudgetCategory.all.where(author_id: current_user.id)
  end

  # GET /budget_categories/1 or /budget_categories/1.json
  def show
    @budget_category = BudgetCategory.includes(:expenses).find(params[:id])
  end

  # GET /budget_categories/new
  def new
    @budget_category = BudgetCategory.new
  end

  # GET /budget_categories/1/edit
  def edit; end

  # POST /budget_categories or /budget_categories.json
  def create
    # @budget_category = current_user.budget_categories.new(budget_category_params)
    @budget_category = BudgetCategory.new(author: current_user, **budget_category_params)

    respond_to do |format|
      if @budget_category.save
        format.html do
          redirect_to budget_categories_path, notice: 'Budget category was successfully created.'
        end
        format.json { render :show, status: :created, location: @budget_category }
        # redirect_to user_budget_categories_path
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /budget_categories/1 or /budget_categories/1.json
  def update
    respond_to do |format|
      if @budget_category.update(budget_category_params)
        format.html do
          redirect_to budget_category_url(@budget_category), notice: 'Budget category was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @budget_category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @budget_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /budget_categories/1 or /budget_categories/1.json
  def destroy
    @budget_category.destroy

    respond_to do |format|
      format.html { redirect_to budget_categories_url, notice: 'Budget category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_budget_category
    @budget_category = BudgetCategory.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def budget_category_params
    params.require(:budget_category).permit(:name, :icon)
  end
end

app/helpers/budget_categories_helper.rb
module BudgetCategoriesHelper
end

app/views/budget_categories/_budget_category.html.erb
<div id="<%= dom_id budget_category %>" class="category">
  <div>
    <%= image_tag budget_category.icon %>
    <p>
      <%= link_to budget_category.name, budget_category_expenses_path(budget_category) %>
    </p>
  </div>
  <p class="total">
    $<%= budget_category.total%>
  </p>

</div>

app/views/budget_categories/_form.html.erb
<%= form_with model: budget_category, url: budget_categories_path do |form| %>
  <div>
    <%= form.text_field :name, placeholder: :name %>
  </div>

  <div>
    <%= form.text_field :icon, placeholder: :icon_link %>
  </div>

  <% if budget_category.errors.any? %>
    <div style="color: red" id="error_explanation">
      <h2><%= pluralize(budget_category.errors.count, "error") %> prohibited this budget_category from being saved:</h2>

      <ul>
        <% budget_category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit "Save" %>
  </div>
<% end %>

app/views/budget_categories/edit.html.erb
<h1>Editing budget category</h1>

<%= render "form", budget_category: @budget_category %>

<br>

<div>
  <%= link_to "Show this budget category", @budget_category %> |
  <%= link_to "Back to budget categories", budget_categories_path %>
</div>

app/views/budget_categories/index.html.erb
<section class="categories">
  <p style="color: green"><%= notice %></p>

  <h1>Budget Categories</h1>

  <div id="budget_categories">
    <% @budget_categories.each do |budget_category| %>
      <%= render budget_category %>
    <% end %>
  </div>

  <div class="new-category">
    <%= link_to "Add New category", new_budget_category_path %>
  </div>
</section>

app/views/budget_categories/new.html.erb
<section class="devise-forms">
<div class="header header-details">
    <%= link_to budget_categories_path do %>
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path d="M109.3 288L480 288c17.7 0 32-14.3 32-32s-14.3-32-32-32l-370.7 0 73.4-73.4c12.5-12.5 12.5-32.8 0-45.3s-32.8-12.5-45.3 0l-128 128c-12.5 12.5-12.5 32.8 0 45.3l128 128c12.5 12.5 32.8 12.5 45.3 0s12.5-32.8 0-45.3L109.3 288z"/></svg>
    <% end %>
    <p>CATEGORY</p>
</div>
  <%= render "form", budget_category: @budget_category %>
  <br>
</section>

app/views/budget_categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @budget_category %>

<div>
  <%= link_to "Edit this budget category", edit_budget_category_path(@budget_category) %> |
  <%= link_to "Back to budget categories", budget_categories_path %>

  <%= link_to 'Add Transaction', new_budget_category_expense_path(@budget_category) %>

  <%= button_to "Destroy this budget category", @budget_category, method: :delete %>
</div>