config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }

  resources :users

  resources :budget_categories do
    resources :expenses
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'splash_screen#index'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :expenses, foreign_key: :author_id, dependent: :destroy
  has_many :budget_categories, foreign_key: :author_id, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_expense, only: %i[show edit update destroy]

  # GET /expenses or /expenses.json
  def index
    @budget_category = BudgetCategory.find(params[:budget_category_id])
    @expenses = @budget_category.expenses.order(created_at: :desc)
    @total = @expenses.sum(:amount)
  end

  # GET /expenses/1 or /expenses/1.json
  def show
    @budget_category = BudgetCategory.find(params[:budget_category_id])
  end

  # GET /expenses/new
  def new
    @budget_categories = BudgetCategory.all.where(author_id: current_user.id)
    @budget_category = BudgetCategory.find(params[:budget_category_id])
    @expense = Expense.new
  end

  # GET /expenses/1/edit
  def edit; end

  # POST /expenses or /expenses.json
  def create
    @budget_category = BudgetCategory.find(params[:budget_category_id])
    @expense = Expense.new(author: current_user, **expense_params)

    respond_to do |format|
      if @expense.save
        format.html do
          redirect_to budget_category_expenses_path(@budget_category), notice: 'Expense was successfully created.'
        end
        format.json { render :show, status: :created, location: @expense }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expenses/1 or /expenses/1.json
  def update
    respond_to do |format|
      if @expense.update(expense_params)
        format.html { redirect_to expense_url(@expense), notice: 'Expense was successfully updated.' }
        format.json { render :show, status: :ok, location: @expense }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1 or /expenses/1.json
  def destroy
    @expense.destroy

    respond_to do |format|
      format.html { redirect_to expenses_url, notice: 'Expense was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_expense
    @expense = Expense.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def expense_params
    params.require(:expense).permit(:name, :amount, budget_category_ids: [])
  end
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/views/expenses/_expense.html.erb
<div id="<%= dom_id expense %>" class="expense">
  <div>
    <p>
      <%= link_to expense.name, budget_category_expense_path(@budget_category, expense) %>
    </p>
    <p class="date">
      <i class="fa-regular fa-calendar"></i>
      <%= expense.time_created %>
    </p>
  </div>

  <p class="amount">
    $<%= expense.amount %>
  </p>

</div>

app/views/expenses/_form.html.erb
<%= form_with model: @expense, url: budget_category_expenses_path(@budget_category) do |form| %>
  <div>
    <%= form.text_field :name, placeholder: :name %>
  </div>

  <div>
    <%= form.text_field :amount, placeholder: :amount %>
  </div>

  <div class="collection">
    <%= form.label :choose_category %>
     <%= form.collection_check_boxes :budget_category_ids, BudgetCategory.all.where(author: current_user), :id, :name, { hide_label: true } %>
  </div>

  <% if expense.errors.any? %>
    <div style="color: red" id="error_explanation">
      <h2><%= pluralize(expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

      <ul>
        <% expense.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit 'Save' %>
  </div>
<% end %>

app/views/expenses/edit.html.erb
<h1>Editing expense</h1>

<%= render "form", expense: @expense %>

<br>

<div>
  <%= link_to "Show this expense", @expense %> |
  <%= link_to "Back to expenses", expenses_path %>
</div>

app/views/expenses/index.html.erb
<section>
  <p style="color: green"><%= notice %></p>

  <div class="header header-details">
    <%= link_to budget_categories_path do %>
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path d="M109.3 288L480 288c17.7 0 32-14.3 32-32s-14.3-32-32-32l-370.7 0 73.4-73.4c12.5-12.5 12.5-32.8 0-45.3s-32.8-12.5-45.3 0l-128 128c-12.5 12.5-12.5 32.8 0 45.3l128 128c12.5 12.5 32.8 12.5 45.3 0s12.5-32.8 0-45.3L109.3 288z"/></svg>
    <% end %>
    <p>DETAILS</p>
  </div>

  <div class="category">
    <div>
      <%= image_tag @budget_category.icon %>
      <p>
        <%= link_to @budget_category.name, budget_category_expenses_path(@budget_category) %>
      </p>
    </div>

</div>

  <div id="expenses">
    <% @expenses.each do |expense| %>
      <%= render expense %>
    <% end %>
  </div>
  <div class="total-container">
  <p>TOTAL PAYMENT</p>
  <p class="total">
      $<%= @budget_category.total%>
  </p>
  </div>

  <div class="new-category">
    <%= link_to "Add New Transaction", new_budget_category_expense_path(@budget_category) %>
  </div>
</section>

app/views/expenses/new.html.erb
<section class="devise-forms">
<div class="header header-details">
    <%= link_to budget_category_expenses_path(@budget_category) do %>
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path d="M109.3 288L480 288c17.7 0 32-14.3 32-32s-14.3-32-32-32l-370.7 0 73.4-73.4c12.5-12.5 12.5-32.8 0-45.3s-32.8-12.5-45.3 0l-128 128c-12.5 12.5-12.5 32.8 0 45.3l128 128c12.5 12.5 32.8 12.5 45.3 0s12.5-32.8 0-45.3L109.3 288z"/></svg>
    <% end %>
    <p>EXPENSE</p>
  </div>

  <%= render "form", expense: @expense %>

  <br>
</section>

app/views/expenses/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @expense %>

<div>
  <%= link_to "Edit this expense", edit_budget_category_expense_path(@expense) %> |
  <%= link_to "Back to expenses", budget_category_expenses_path %>

  <%= button_to "Destroy this expense", budget_category_expense_path, method: :delete %>
</div>